[package]
name = "libriscv"
version = "0.3.0"
edition = "2024"
authors = ["nemurubaka <cijiugechu@gmail.com>"]
description = "Safe wrapper for libriscv_sys, a fast RISC-V sandbox emulator"
license = "BSD-3-Clause"
keywords = ["riscv", "emulator", "vm", "ffi", "bindings"]
readme = "README.md"
repository = "https://github.com/cijiugechu/libriscv"
exclude = [
    "examples/advanced/riscv_program",
    "examples/advanced/rust_program",
]

[workspace]
members = ["libriscv-macros", "libriscv-sys", "."]

[dependencies]
bytemuck = { version = "1.24", features = ["derive"], optional = true }
libriscv_sys = { version = "0.2.0", path = "libriscv-sys" }
libriscv-macros = { version = "0.2.0", path = "libriscv-macros" }

[features]
default = ["bytemuck"]
bindgen = ["libriscv_sys/bindgen"]
binary-translation = ["libriscv_sys/binary-translation"]
bytemuck = ["dep:bytemuck"]
