[package]
name = "libriscv-macros"
version = "0.2.0"
edition = "2024"
authors = ["nemurubaka <cijiugechu@gmail.com>"]
description = "Proc-macro helpers for libriscv"
license = "BSD-3-Clause"
keywords = ["riscv", "proc-macro", "ffi", "macros"]
readme = "README.md"
repository = "https://github.com/cijiugechu/libriscv"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
trybuild = "1.0"
libriscv = { path = ".." }
